apiVersion: v1
kind: ReplicationController
metadata:
  name: bar-rc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bar
    spec:
      containers:
      - name: bar-container
        image: <CONTAINER>
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http-server
